/**
 * Created by David Maser on 31/05/2017.
 */
import nm from '../Templates';
export const Translate = {
  yNodes:[
    {
      tag:'create',
      accepts:'all',
      excludes:null,
      strict:false
    },{
      tag:'constant',
      accepts:'const',
      modifiers:[
        {
          tag:'',
          arguments:''
        }
      ],
      excludes:null,
      strict:true
    },{
      tag:'var',
      accepts:'var',
      modifiers:[
        {
          tag:'',
          arguments:''
        }
      ],
      excludes:null,
      strict:true
    },{
      tag:'object',
      accepts:'object',
      modifiers:[
        {
          tag:'',
          arguments:''
        }
      ],
      excludes:null,
      strict:true
    },{
      tag:'array',
      accepts:'array',
      modifiers:[
        {
          tag:'',
          arguments:''
        }
      ],
      excludes:null,
      strict:true
    }
  ],
  init:function(){
    nm('haha');
    console.log(this.yNodes);
  }
};